clean up functionalities, add OS detection, add FreeBSD support

diff --git a/ofman b/ofman
--- a/ofman
+++ b/ofman
@@ -1,4 +1,4 @@
-#!/usr/bin/sh
+#!/usr/bin/env sh
 
 # NEVER install OF as root
 # don't even get to the first line of actual code
@@ -25,13 +25,6 @@ RED=""
 BLUE=""
 GREEN=""
 CLEAR=""
-
-if [ "$(tput colors)" -eq 256 ] && [ -z "$NO_COLORS" ]; then
-    RED="$(tput setaf 9)"
-    BLUE="$(tput setaf 14)"
-    GREEN="$(tput setaf 10)"
-    CLEAR="$(tput sgr0)"
-fi
 
 err()
 {
@@ -60,34 +53,33 @@ help_message()
 
 main()
 {
-    # try fetching the Distro we are on
-    if [ -f "/etc/os-release" ]; then
-        . /etc/os-release
-    fi
+    detect_os
+
+    setup_colors
 
     load_config
     check_svn
 
     if [ -z "$SKIP_DEPENDENCIES" ]; then
-        resolve_dependencies $ID;
+        resolve_dependencies $DISTRO;
     fi
 
 
     case $1 in
         install)
-            checkout_repo $OF_REPO $OF_DIR
+            checkout_repo "$OF_REPO" "$OF_DIR"
             ;;
 
         uninstall)
-            delete_repo $OF_REPO $OF_DIR
+            delete_repo "$OF_REPO" "$OF_DIR"
             ;;
 
         update)
-            update_repo $OF_REPO $OF_DIR
+            update_repo "$OF_REPO" "$OF_DIR"
             ;;
 
         run)
-            run $OF_DIR
+            run "$OF_DIR"
             ;;
 
         config)
@@ -98,6 +90,61 @@ main()
             help_message
             ;;
     esac
+}
+
+detect_os()
+{
+    DISTRO=""
+
+    if [ -z "$OSTYPE" ]; then
+        OSTYPE="$(uname)"
+    fi
+
+    case $OSTYPE in
+
+        linux-gnu | Linux)
+
+            if [ -f "/etc/os-release" ]; then
+                . /etc/os-release
+            fi
+
+            for file in /etc/lsb-release /usr/lib/os-release \
+                        /etc/os-release  /etc/openwrt_release; do
+                if [ -f "$file" ]; then
+                    . $file
+                    break
+                fi
+            done
+
+            DISTRO="$ID"
+            ;;
+
+        *BSD)
+            $DISTRO="$OSTYPE"
+            ;;
+
+        *)
+            echo "Unknown OS detected."
+            echo "It cannot be ensured everything works correctly"
+            ;;
+    esac
+}
+
+setup_colors()
+{
+    if [ -n "$(which tty 2> /dev/null)"  ]; then
+        tty -s
+    else
+        # can't check if we are in a tty, assume the worst
+        false
+    fi
+
+    if [ "$?" -eq 0 ] && [ -z "$NO_COLOR" ] && [ "$(tput colors)" -eq 256 ]; then
+        RED="$(tput setaf 9)"
+        BLUE="$(tput setaf 14)"
+        GREEN="$(tput setaf 10)"
+        CLEAR="$(tput sgr0)"
+    fi
 }
 
 load_config()
@@ -147,8 +194,6 @@ resolve_dependencies()
 {
     info "Installing dependencies"
 
-    # should we really assume the user has
-    # a system with a updated repo cache?
     case $1 in
         fedora)
             sudo dnf install subversion -y || err "Couldn't install subversion using dnf."
@@ -168,6 +213,10 @@ resolve_dependencies()
             sudo xbps-install -Sy subversion || err "Couldn't install subversion using xbps."
             ;;
 
+        FreeBSD)
+            sudo pkg -y install subversion || err "Couldn't install subversion using pkg."
+            ;;
+
         *)
             err "$SPACING Couldn't install dependencies."
             err "$SPACING Install the following dependencies yourself:"
@@ -178,9 +227,16 @@ resolve_dependencies()
 
 checkout_repo()
 {
-    info "Installing OpenFortress to $OF_DIR"
+    if [ -d "$2" ]; then
+        err "checkout already exists"
+        return
+    fi
 
-    $SVN $CHECKOUT $1 $2
+    info "Installing OpenFortress to this directory"
+    echo "\"$2\""
+    echo ""
+
+    $SVN $CHECKOUT "$1" "$2"
 
     fin "OpenFortress installed!"
 }
@@ -189,6 +245,7 @@ delete_repo()
 {
     err "Are you sure you want to delete this directory? [y/n]"
     echo "\"$2\""
+    echo ""
 
     while [ true ]
     do
@@ -214,6 +271,11 @@ delete_repo()
 
 update_repo()
 {
+    if [ ! -d "$2" ]; then
+        err "checkout does not exist"
+        return
+    fi
+
     info "Updating OpenFortress"
 
     # we cannot push throug the directory stack
